### ISSUE TITLE
Bot Randomly Crashes

### ISSUE THREAD

**Issue by Tnology** [Tnology/TnologyDiscordBot#6]
### Bug Report
The bot will sometimes crash at random with an "Uncaught DiscordAPIError" as seen below:

```
error: Uncaught DiscordAPIError:
GET /guilds/471700758354460672/members/1017989345292058656 returned 404
(10007) Unknown Member
      throw new DiscordAPIError({
            ^
    at BucketHandler.execute (https://raw.githubusercontent.com/harmonyland/harmony/daca400ae9feab19604381abddbdab16aa1ede2b/src/rest/bucket.ts:224:13)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async BucketHandler.push (https://raw.githubusercontent.com/harmonyland/harmony/daca400ae9feab19604381abddbdab16aa1ede2b/src/rest/bucket.ts:55:13)
    at async RESTManager.make (https://raw.githubusercontent.com/harmonyland/harmony/daca400ae9feab19604381abddbdab16aa1ede2b/src/rest/manager.ts:236:12)
    at async RESTManager.get (https://raw.githubusercontent.com/harmonyland/harmony/daca400ae9feab19604381abddbdab16aa1ede2b/src/rest/manager.ts:259:12)
    at async MemberRolesManager._resolveMemberPayload (https://raw.githubusercontent.com/harmonyland/harmony/daca400ae9feab19604381abddbdab16aa1ede2b/src/managers/memberRoles.ts:22:23)
    at async MemberRolesManager.array (https://raw.githubusercontent.com/harmonyland/harmony/daca400ae9feab19604381abddbdab16aa1ede2b/src/managers/memberRoles.ts:50:17)
[root@vps TnologyDiscordBot]# 
```

### Expected Behavior
The expected behavior is the bot not crashing at random.

### How to Reproduce
I can't seem to find a trigger for this error, it just seems to happen at random while the bot is running. However, I have noticed that there is no "main.ts" within the error - only Harmony's bucket.ts and memberRoles.ts and similar. The crash isn't immediate, it takes some time with the bot running for the bot to crash.

### Additional Context
I posted a screenshot of this error in Harmony's official Discord server, and one of the developers replied with "huh" - I said "I suppose this is an issue with Harmony?" to which they said "probably.."

**Comment by Tnology** [comment]
Seems like an issue with Harmony, opened an issue there: https://github.com/harmonyland/harmony/issues/371
